name: CSU Library Reserve

on:
  workflow_dispatch:

  schedule:
    - cron: '45 21 * * *'  # 每天21:45 (UTC) 触发, 对应北京时间 5:45

jobs:
  reserve:
    runs-on: ubuntu-latest
    permissions: # 添加这一行
      contents: write # 添加这一行，注意这里的缩进

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Reserve
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        python3 helper.py --action 'reserve' --userid $user --password $pwd
    - name: Commit
      run: |
        git config --global user.email founder.yu@foxmail.com
        git config --global user.name founder-yu
        git add .
        git commit -m "Update library.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
